name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - id: make_version_string
      uses: sandersaares-actions/make-time-based-version-string@main
    - id: make_nuget_version_string
      uses: sandersaares-actions/make-time-based-nuget-version-string@main
      with:
        versionstring: ${{ steps.make_version_string.outputs.VERSION_STRING }}
    - uses: sandersaares-actions/expand-tokens@master
      env:
        VERSION_STRING: ${{ steps.make_nuget_version_string.outputs.NUGET_VERSION_STRING }}
      with:
        path: Koek.CodeAnalysis.nuspec
    - name: Package
      run: nuget pack Koek.CodeAnalysis.nuspec
    - uses: actions/upload-artifact@v2
      with:
        name: nupkg
        path: '*.nupkg'
    - name: Publish
      run: nuget push -ApiKey ${{ secrets.nuget_api_key }} -Source https://api.nuget.org/v3/index.json *.nupkg